nginx:
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://gelf:5000"
  restart: always
  image: nginx
  ports:
  - "${public_port}:80"
  external_links:
  - ${logstash_link}:gelf
  labels:
    io.rancher.container.hostname_override: container_name