nginx:
    image: nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    image: tomcat
    links:
        - memcached
    ports:
        - "8080"
node2:
    image: tomcat
    links:
        - memcached
    ports:
        - "8080"
node3:
    image: tomcat
    links:
        - memcached
    ports:
        - "8080"
memcached:
    image: memcached
    ports:
        - "11211"