.catalog:
  name: nginx and redis
  version: 0.0.1
  description: template to deploy 3 nginx instances and redis
  uuid: 001
  minimum_rancher_version: # The minimum version of Rancher that supports the template
  questions: #Used to request user input for configuration options
