name: Dummy test stack
description: |
  # Description of the Catalog Entry
version: 0.0.1
category: test
maintainer: # The maintainer of the catalog entry
license: # The license
projectURL: # A URL related to the catalog entry
